on:
    push:
        branches:
            - main

# 强制使用 Node.js 24，消除警告
env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Install SSH key
              uses: webfactory/ssh-agent@v0.9.1
              with:
                  ssh-private-key: ${{ secrets.TAI_SSH_PRIVATE_KEY }}

            - name: Add known hosts
              run: ssh-keyscan ${{ secrets.TAI_SERVER_IP }} > ~/.ssh/known_hosts

            - name: Deploy to server
              env:
                  # 数据库配置
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
                  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
                  # 正确拼接数据库连接串
                  POSTGRES_URL: "postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}"
                  # API KEY
                  DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
                  DOUBAO_API_KEY: ${{ secrets.DOUBAO_API_KEY }}
                  QIANWEN_API_KEY: ${{ secrets.QIANWEN_API_KEY }}
              # 执行部署脚本
              run: ssh -o StrictHostKeyChecking=no ${{ secrets.TAI_USER }}@${{ secrets.TAI_SERVER_IP }} 'bash -s' < ./deploy.sh
